server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index TravelLogik.html;

    location = /healthz {
        add_header Content-Type text/plain;
        return 200 "ok\n";
    }

    location / {
        try_files $uri $uri/ /TravelLogik.html;
    }

    location ~* \.(?:js|css|html)$ {
        try_files $uri =404;
        add_header Cache-Control "no-cache";
    }
}
